update cli interface

diff --git a/scripts/add-if-present b/scripts/add-if-present
--- a/scripts/add-if-present
+++ b/scripts/add-if-present
@@ -1,8 +1,10 @@
 #!/usr/bin/env bash
 
+set -e
+
 if [ -z "$1" ]; then
-    echo "ERROR: missing <manifest>!" >&2
-    exit 1
+  echo "ERROR: missing <manifest>!" >&2
+  exit 1
 fi
 
 PKG="$1"
@@ -14,13 +16,13 @@ if [ -z "$1" ]; then exit 0; fi
 ADD=''
 
 while (( "$#" )); do
-    if [ -e $1 ]; then
-	ADD="$ADD $1"
-    fi
-    shift
+  if [ -e $1 ]; then
+    ADD="$ADD $1"
+  fi
+  shift
 done
 
 if [ -n "$ADD" ]; then
-    sed -E -i '' "s/(^BuiltWith: .*)\$/\1$ADD/" "$PKG"
-    grep ^BuiltWith: "$PKG"
+  sed -E -i "s/(^BuiltWith: .*)\$/\1$ADD/" "$PKG"
+  grep ^BuiltWith: "$PKG"
 fi
